// Generated by reflectclient/wrap at 2017-07-09 19:30:28.568852955 +0000 UTC
package giantbombservicewrapper

import (
	"github.com/dforsyth/reflectclient-giantbomb"
)

type GiantBombServiceWrapper struct {
	service *giantbomb.GiantBombService
}

func (r *GiantBombServiceWrapper) Videos(pos0 *giantbomb.VideosParams) (*giantbomb.VideoListResponse, error) {
	return r.service.Videos(pos0)
}

func (r *GiantBombServiceWrapper) Video(pos0 *giantbomb.VideoParams) (*giantbomb.VideoResponse, error) {
	return r.service.Video(pos0)
}

func (r *GiantBombServiceWrapper) VideoTypes() (*giantbomb.VideoTypesResponse, error) {
	return r.service.VideoTypes()
}

func (r *GiantBombServiceWrapper) Validate(pos0 *giantbomb.ValidateParams) (*giantbomb.ApiKeyResponse, error) {
	return r.service.Validate(pos0)
}

func (r *GiantBombServiceWrapper) Search(pos0 *giantbomb.SearchParams) (*giantbomb.SearchListResponse, error) {
	return r.service.Search(pos0)
}

func (r *GiantBombServiceWrapper) GetGiantBombService() *giantbomb.GiantBombService {
	return r.service
}

func WrapGiantBombService(service *giantbomb.GiantBombService) *GiantBombServiceWrapper {
	return &GiantBombServiceWrapper{service}
}
